create table profiles (
  id uuid primary key references auth.users,
  created_at timestamptz default now()
);

create table vault_items (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id),
  title text not null,
  username text,
  ciphertext bytea not null,
  iv bytea not null,
  salt bytea not null,
  url text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table vault_items enable row level security;
create policy "User owns item"
  on vault_items for all
  using (auth.uid() = user_id);